import Navbar from "./Navbar/Navbar";
import Hero from "./Hero/Hero";
import About from "./About/About";
import Services from "./Services/Services";
import Tech from "./Tech/Tech";
import Process from "./Process/Process";
import Join from "./Join/Join";
import Footer from "./Footer/Footer";
import Contact from "./Contact/Contact";
export { Navbar, Hero, About, Services, Tech, Process, Join, Footer, Contact };
