import Navbar from "./Navbar/Navbar";
import Hero from "./Hero/Hero";
import About from "./About/About";
import Services from "./Services/Services";
import Tech from "./Tech/Tech";
import Process from "./Process/Process";
import Join from "./Join/Join";
import Footer from "./Footer/Footer";
import Service from "./Service/Service";
export { Navbar, Hero, About, Services, Tech, Process, Join, Footer, Service};
